### PR TITLE
[FEATURE] Added self in uwus/owos/tildes as mentioned in #90

### LINKED ISSUE #90: [FEATURE] Show current user position in uwus/owos/tildes
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The user should show in the `~uwus` (and others) leaderboards if they aren't in the top 10.

Here's an example:
```
 1 :: ...
 2 :: ...
 3 :: ...
 4 :: ...
 5 :: ...
 6 :: ...
 7 :: ...
 8 :: ...
 9 :: ...
10 :: ...
====================
99 :: BadBoyHaloCat#1826 with 2 uwus
```

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by LostNuke**
**Does this Pull Request fix an issue? If so, please mention the issue.**
Closes #90 

**Describe your changes.**
I added the ===== line and then added the line to mention own users placing, if not in top 10

**Describe alternatives you've considered**
None

**Additional context**
None

### CODE REVIEW

**Comment by thetayloredman** [comment]
in the future change `#90` to `Fixes #90` or `Closes #90` so it closes for you...

**Comment by LostNuke** [comment]
OH sorry, didnt know about that

**Comment by thetayloredman** [comment]
There's a small problem with rendering it like this:
```
10 :: ...
101 :: ...
```
Let's not screw up this code, and just leave it as is... Lol

**Comment by LostNuke** [comment]
I see the problem xD
That would be an annoying fix

**Comment by LostNuke** [comment]
But dont forget there is an ====== as a seperator so I guess it wouldnt be too horrible lol

**Comment by thetayloredman** [comment]
We would have to do padding on it and that would make this holy file even worse.

You still need to do this to owos and tildes however.

**Comment by LostNuke** [comment]
Holy... there is more xD Hmmm yeah thats easy to add in Gimme a few

**Comment by LostNuke** [comment]
There we go

**Comment by thetayloredman** [comment]
Please `npm i`, then `npm run prettier`.

**Comment by LostNuke** [comment]
I did as I was commanded

**Comment by thetayloredman** [comment]
LGTM!

**Pull request merged**
