### PR TITLE
feat(cuties): remove Nepgfurmixpro from cuties

### PR DESCRIPTION
**Pull request by Nepgfurmixpro**
Because im not cute.

**Does this Pull Request fix an issue? If so, please mention the issue.**
N/A

**Describe your changes.**
What did you change?

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the PR here.

### CODE REVIEW

**Comment by thetayloredman** [comment]
If you say so...

**Comment by thetayloredman** [comment]
CI: *fails*
Me: *Oh no*

**Comment by Nepgfurmixpro** [comment]
> CI: _fails_
> Me: _Oh no_
> EDIT: it seems to be github's fault

yea lmao i didn't even edit code only a json thing

**Comment by thetayloredman** [comment]
> > CI: _fails_
> > Me: _Oh no_
> > EDIT: it seems to be github's fault
> 
> yea lmao i didn't even edit code only a json thing

Looking at the log, `checkout` failed, which is GH's fault (it pulls the latest PR code before checking it)

**Comment by thetayloredman** [comment]
Also, I encourage you to add yourself to the Contributors table by running `@all-contributors add @Nepgfurmixpro for code`

**Comment by Nepgfurmixpro** [comment]
@all-contributors please add @Nepgfurmixpro for code

**Pull request merged**
