### PR TITLE
[BUG] Added split option to uwuify (#67)

### LINKED ISSUE #97: [BUG] ~uwuify runs with 2000+ char text
**Describe the bug**
~uwuify can result in long text, causing errors.

**To Reproduce**

1. Run '`~uwuify ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length`'
2. See error

**Expected behavior**
The bot gives a warning or splits the text

**Actual Behavior**
Errors

**Screenshots**
None

**Additional context**
@Shadowplays4k reported this

### PR DESCRIPTION
**Pull request by LostNuke**
**Does this Pull Request fix an issue? If so, please mention the issue.**
Closes #97 

**Describe your changes.**
I added {split: true} to the send method in uwuify.js

**Describe alternatives you've considered**
None

**Additional context**
None

### CODE REVIEW

**Comment by thetayloredman** [comment]
I would use a split divider of `...` on start and end so it renders as

```
text1...
...text2
```

**Comment by LostNuke** [comment]
Ye, lol didnt know it had that xD Added it now

**Comment by thetayloredman** [comment]
Does prepend decrease the length and account for the "..." being added?

**Comment by LostNuke** [comment]
I went through the code and if I read it right it seems like it does take that in account

**Comment by thetayloredman** [comment]
> I went through the code and if I read it right it seems like it does take that in account

Sounds good!

**Review by thetayloredman — APPROVED** [review]

**Comment by Alcremie** [comment]
I'm honestly not really sure why we're opting for splitting when messages that should be uwuified probably wouldn't go too much over 2000 characters anyways, considering the character limit for users sending messages anyways, but I guess this works...

**Comment by LostNuke** [comment]
> I'm honestly not really sure why we're opting for splitting when messages that should be uwuified probably wouldn't go too much over 2000 characters anyways, considering the character limit for users sending messages anyways, but I guess this works...

I mean tbh, I also don't exactly understand why. Since with removing the pre text, it shouldn't have any issue anymore. But I guess there isn't really anything bad with having it split messages, this I'd say it is a bit safer. I mean if we really wanna go further we could allow adding a .txt message that will get uwufied

**Comment by thetayloredman** [comment]
> Since with removing the pre text, it shouldn't have any issue anymore.

The uwuifier internally adds actions like *runs away* and faces like UwU and s-tutters and changes esclamations!!11 so it's always a problem.

**Comment by Alcremie** [comment]
> > Since with removing the pre text, it shouldn't have any issue anymore.
> 
> The uwuifier internally adds actions like _runs away_ and faces like UwU and s-stutters and changes esclamations!!11 so it's always a problem.

Oh, that explains a lot. Okay, I think splitting is alright, then.



> > I'm honestly not really sure why we're opting for splitting when messages that should be uwuified probably wouldn't go too much over 2000 characters anyways, considering the character limit for users sending messages anyways, but I guess this works...
> 
> I mean tbh, I also don't exactly understand why. Since with removing the pre text, it shouldn't have any issue anymore. But I guess there isn't really anything bad with having it split messages, this I'd say it is a bit safer. I mean if we really wanna go further we could allow adding a .txt message that will get uwufied

I would prefer reading from a hastebin/hatebin/pastie.io link to reading a text file, personally. All of them read in pretty much the same way due to being built on the same API and it just seems a little safer, though perhaps make this available to select users who probably shouldn't use it to avoid inappropriate/bad content.

**Comment by thetayloredman** [comment]
Here's a real example:

**IN:**
```
[BEEP] [BEEP] [BEEP] This is a test of the national UwUification system. I'm testing this for the following reason: ProtoBot PR Example. -- Foxley is now officially a cutie. -- PR: thetayloredman/ProtoBot#117 -- Yes I do be a furry lol -- Fun fact: charmines is a furry -- I just needa make this longer...... -- codic is not cute sorry -- i now have vulpro.is-inside.me -- is this long enough? [BEEP] [BEEP] [BEEP]
```
**OUT:**
```
[BEEP] [BEEP] [BEEP] This is a test of the x3 nyationyaw UwUification system. I'm testing this fow the x3 fowwowing reason: PwotoBot PW Exampwe. -- Foxwey is nyow *whispers to self* officiawwy a cutie. *sweats* -- PR: thetaywowedman/PwotoBot#117 -- Yes I do be a fuwwy wow -- Fun fact: chawminyes is a fuwwy -- I just *blushes* nyeeda make this wongew...... -- codic is nyot c-cute sowwy *huggles tightly* -- i nyow *whispers to self* have vuwpwo.is-inside.me -- is this w-wong enyough?!?! [BEEP] [BEEP] [BEEP]
```

**Pull request merged**
